name: Windows RDP Server

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    steps:
      - name: Set ngrok auth token
        run: |
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Start ngrok TCP tunnel on port 3389
        run: start /b ngrok tcp 3389
      - name: Wait for ngrok to start
        run: Start-Sleep -Seconds 10

      - name: Set password for runneradmin user
        shell: powershell
        run: |
          $Password = ConvertTo-SecureString "Runner@123" -AsPlainText -Force
          Set-LocalUser -Name "runneradmin" -Password $Password

      - name: Get ngrok public URL
        shell: powershell
        run: |
          function Get-NgrokUrl {
            param ([int]$attempt)
            try {
              $url = "http://localhost:4040/api/tunnels"
              $response = Invoke-RestMethod -Uri $url -TimeoutSec 5
              if ($response.tunnels.Length -gt 0) {
                return $response.tunnels[0].public_url -replace "tcp://", ""
              }
              return $null
            }
            catch {
              return $null
            }
          }

          $maxAttempts = 10
          $attempt = 0
          $connected = $false

          do {
            $attempt++
            $url = Get-NgrokUrl -attempt $attempt
            if ($url) {
              Write-Host "RDP Connection Details:"
              Write-Host "------------------------"
              Write-Host "Host: $url"
              Write-Host "Username: runneradmin"
              Write-Host "Password: Runner@123"
              Write-Host "------------------------"
              $connected = $true
              break
            }
            Start-Sleep -Seconds 5
          } while ($attempt -lt $maxAttempts -and -not $connected)

          if (-not $connected) {
            Write-Host "Failed to get Ngrok URL"
            exit 1
          }
